package com.nju.qrs.model;

import java.util.ArrayList;
import java.util.List;

public class StockExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stock
     *
     * @mbggenerated Wed Apr 12 19:45:01 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stock
     *
     * @mbggenerated Wed Apr 12 19:45:01 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stock
     *
     * @mbggenerated Wed Apr 12 19:45:01 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbggenerated Wed Apr 12 19:45:01 CST 2017
     */
    public StockExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbggenerated Wed Apr 12 19:45:01 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbggenerated Wed Apr 12 19:45:01 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbggenerated Wed Apr 12 19:45:01 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbggenerated Wed Apr 12 19:45:01 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbggenerated Wed Apr 12 19:45:01 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbggenerated Wed Apr 12 19:45:01 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbggenerated Wed Apr 12 19:45:01 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbggenerated Wed Apr 12 19:45:01 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbggenerated Wed Apr 12 19:45:01 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbggenerated Wed Apr 12 19:45:01 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table stock
     *
     * @mbggenerated Wed Apr 12 19:45:01 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andStocknumIsNull() {
            addCriterion("stockNum is null");
            return (Criteria) this;
        }

        public Criteria andStocknumIsNotNull() {
            addCriterion("stockNum is not null");
            return (Criteria) this;
        }

        public Criteria andStocknumEqualTo(String value) {
            addCriterion("stockNum =", value, "stocknum");
            return (Criteria) this;
        }

        public Criteria andStocknumNotEqualTo(String value) {
            addCriterion("stockNum <>", value, "stocknum");
            return (Criteria) this;
        }

        public Criteria andStocknumGreaterThan(String value) {
            addCriterion("stockNum >", value, "stocknum");
            return (Criteria) this;
        }

        public Criteria andStocknumGreaterThanOrEqualTo(String value) {
            addCriterion("stockNum >=", value, "stocknum");
            return (Criteria) this;
        }

        public Criteria andStocknumLessThan(String value) {
            addCriterion("stockNum <", value, "stocknum");
            return (Criteria) this;
        }

        public Criteria andStocknumLessThanOrEqualTo(String value) {
            addCriterion("stockNum <=", value, "stocknum");
            return (Criteria) this;
        }

        public Criteria andStocknumLike(String value) {
            addCriterion("stockNum like", value, "stocknum");
            return (Criteria) this;
        }

        public Criteria andStocknumNotLike(String value) {
            addCriterion("stockNum not like", value, "stocknum");
            return (Criteria) this;
        }

        public Criteria andStocknumIn(List<String> values) {
            addCriterion("stockNum in", values, "stocknum");
            return (Criteria) this;
        }

        public Criteria andStocknumNotIn(List<String> values) {
            addCriterion("stockNum not in", values, "stocknum");
            return (Criteria) this;
        }

        public Criteria andStocknumBetween(String value1, String value2) {
            addCriterion("stockNum between", value1, value2, "stocknum");
            return (Criteria) this;
        }

        public Criteria andStocknumNotBetween(String value1, String value2) {
            addCriterion("stockNum not between", value1, value2, "stocknum");
            return (Criteria) this;
        }

        public Criteria andStocknameIsNull() {
            addCriterion("stockName is null");
            return (Criteria) this;
        }

        public Criteria andStocknameIsNotNull() {
            addCriterion("stockName is not null");
            return (Criteria) this;
        }

        public Criteria andStocknameEqualTo(String value) {
            addCriterion("stockName =", value, "stockname");
            return (Criteria) this;
        }

        public Criteria andStocknameNotEqualTo(String value) {
            addCriterion("stockName <>", value, "stockname");
            return (Criteria) this;
        }

        public Criteria andStocknameGreaterThan(String value) {
            addCriterion("stockName >", value, "stockname");
            return (Criteria) this;
        }

        public Criteria andStocknameGreaterThanOrEqualTo(String value) {
            addCriterion("stockName >=", value, "stockname");
            return (Criteria) this;
        }

        public Criteria andStocknameLessThan(String value) {
            addCriterion("stockName <", value, "stockname");
            return (Criteria) this;
        }

        public Criteria andStocknameLessThanOrEqualTo(String value) {
            addCriterion("stockName <=", value, "stockname");
            return (Criteria) this;
        }

        public Criteria andStocknameLike(String value) {
            addCriterion("stockName like", value, "stockname");
            return (Criteria) this;
        }

        public Criteria andStocknameNotLike(String value) {
            addCriterion("stockName not like", value, "stockname");
            return (Criteria) this;
        }

        public Criteria andStocknameIn(List<String> values) {
            addCriterion("stockName in", values, "stockname");
            return (Criteria) this;
        }

        public Criteria andStocknameNotIn(List<String> values) {
            addCriterion("stockName not in", values, "stockname");
            return (Criteria) this;
        }

        public Criteria andStocknameBetween(String value1, String value2) {
            addCriterion("stockName between", value1, value2, "stockname");
            return (Criteria) this;
        }

        public Criteria andStocknameNotBetween(String value1, String value2) {
            addCriterion("stockName not between", value1, value2, "stockname");
            return (Criteria) this;
        }

        public Criteria andMarketclosedIsNull() {
            addCriterion("marketClosed is null");
            return (Criteria) this;
        }

        public Criteria andMarketclosedIsNotNull() {
            addCriterion("marketClosed is not null");
            return (Criteria) this;
        }

        public Criteria andMarketclosedEqualTo(Boolean value) {
            addCriterion("marketClosed =", value, "marketclosed");
            return (Criteria) this;
        }

        public Criteria andMarketclosedNotEqualTo(Boolean value) {
            addCriterion("marketClosed <>", value, "marketclosed");
            return (Criteria) this;
        }

        public Criteria andMarketclosedGreaterThan(Boolean value) {
            addCriterion("marketClosed >", value, "marketclosed");
            return (Criteria) this;
        }

        public Criteria andMarketclosedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("marketClosed >=", value, "marketclosed");
            return (Criteria) this;
        }

        public Criteria andMarketclosedLessThan(Boolean value) {
            addCriterion("marketClosed <", value, "marketclosed");
            return (Criteria) this;
        }

        public Criteria andMarketclosedLessThanOrEqualTo(Boolean value) {
            addCriterion("marketClosed <=", value, "marketclosed");
            return (Criteria) this;
        }

        public Criteria andMarketclosedIn(List<Boolean> values) {
            addCriterion("marketClosed in", values, "marketclosed");
            return (Criteria) this;
        }

        public Criteria andMarketclosedNotIn(List<Boolean> values) {
            addCriterion("marketClosed not in", values, "marketclosed");
            return (Criteria) this;
        }

        public Criteria andMarketclosedBetween(Boolean value1, Boolean value2) {
            addCriterion("marketClosed between", value1, value2, "marketclosed");
            return (Criteria) this;
        }

        public Criteria andMarketclosedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("marketClosed not between", value1, value2, "marketclosed");
            return (Criteria) this;
        }

        public Criteria andCurrentpriceIsNull() {
            addCriterion("currentPrice is null");
            return (Criteria) this;
        }

        public Criteria andCurrentpriceIsNotNull() {
            addCriterion("currentPrice is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentpriceEqualTo(Float value) {
            addCriterion("currentPrice =", value, "currentprice");
            return (Criteria) this;
        }

        public Criteria andCurrentpriceNotEqualTo(Float value) {
            addCriterion("currentPrice <>", value, "currentprice");
            return (Criteria) this;
        }

        public Criteria andCurrentpriceGreaterThan(Float value) {
            addCriterion("currentPrice >", value, "currentprice");
            return (Criteria) this;
        }

        public Criteria andCurrentpriceGreaterThanOrEqualTo(Float value) {
            addCriterion("currentPrice >=", value, "currentprice");
            return (Criteria) this;
        }

        public Criteria andCurrentpriceLessThan(Float value) {
            addCriterion("currentPrice <", value, "currentprice");
            return (Criteria) this;
        }

        public Criteria andCurrentpriceLessThanOrEqualTo(Float value) {
            addCriterion("currentPrice <=", value, "currentprice");
            return (Criteria) this;
        }

        public Criteria andCurrentpriceIn(List<Float> values) {
            addCriterion("currentPrice in", values, "currentprice");
            return (Criteria) this;
        }

        public Criteria andCurrentpriceNotIn(List<Float> values) {
            addCriterion("currentPrice not in", values, "currentprice");
            return (Criteria) this;
        }

        public Criteria andCurrentpriceBetween(Float value1, Float value2) {
            addCriterion("currentPrice between", value1, value2, "currentprice");
            return (Criteria) this;
        }

        public Criteria andCurrentpriceNotBetween(Float value1, Float value2) {
            addCriterion("currentPrice not between", value1, value2, "currentprice");
            return (Criteria) this;
        }

        public Criteria andChangeamountIsNull() {
            addCriterion("changeAmount is null");
            return (Criteria) this;
        }

        public Criteria andChangeamountIsNotNull() {
            addCriterion("changeAmount is not null");
            return (Criteria) this;
        }

        public Criteria andChangeamountEqualTo(Float value) {
            addCriterion("changeAmount =", value, "changeamount");
            return (Criteria) this;
        }

        public Criteria andChangeamountNotEqualTo(Float value) {
            addCriterion("changeAmount <>", value, "changeamount");
            return (Criteria) this;
        }

        public Criteria andChangeamountGreaterThan(Float value) {
            addCriterion("changeAmount >", value, "changeamount");
            return (Criteria) this;
        }

        public Criteria andChangeamountGreaterThanOrEqualTo(Float value) {
            addCriterion("changeAmount >=", value, "changeamount");
            return (Criteria) this;
        }

        public Criteria andChangeamountLessThan(Float value) {
            addCriterion("changeAmount <", value, "changeamount");
            return (Criteria) this;
        }

        public Criteria andChangeamountLessThanOrEqualTo(Float value) {
            addCriterion("changeAmount <=", value, "changeamount");
            return (Criteria) this;
        }

        public Criteria andChangeamountIn(List<Float> values) {
            addCriterion("changeAmount in", values, "changeamount");
            return (Criteria) this;
        }

        public Criteria andChangeamountNotIn(List<Float> values) {
            addCriterion("changeAmount not in", values, "changeamount");
            return (Criteria) this;
        }

        public Criteria andChangeamountBetween(Float value1, Float value2) {
            addCriterion("changeAmount between", value1, value2, "changeamount");
            return (Criteria) this;
        }

        public Criteria andChangeamountNotBetween(Float value1, Float value2) {
            addCriterion("changeAmount not between", value1, value2, "changeamount");
            return (Criteria) this;
        }

        public Criteria andPricechangeratioIsNull() {
            addCriterion("priceChangeRatio is null");
            return (Criteria) this;
        }

        public Criteria andPricechangeratioIsNotNull() {
            addCriterion("priceChangeRatio is not null");
            return (Criteria) this;
        }

        public Criteria andPricechangeratioEqualTo(Double value) {
            addCriterion("priceChangeRatio =", value, "pricechangeratio");
            return (Criteria) this;
        }

        public Criteria andPricechangeratioNotEqualTo(Double value) {
            addCriterion("priceChangeRatio <>", value, "pricechangeratio");
            return (Criteria) this;
        }

        public Criteria andPricechangeratioGreaterThan(Double value) {
            addCriterion("priceChangeRatio >", value, "pricechangeratio");
            return (Criteria) this;
        }

        public Criteria andPricechangeratioGreaterThanOrEqualTo(Double value) {
            addCriterion("priceChangeRatio >=", value, "pricechangeratio");
            return (Criteria) this;
        }

        public Criteria andPricechangeratioLessThan(Double value) {
            addCriterion("priceChangeRatio <", value, "pricechangeratio");
            return (Criteria) this;
        }

        public Criteria andPricechangeratioLessThanOrEqualTo(Double value) {
            addCriterion("priceChangeRatio <=", value, "pricechangeratio");
            return (Criteria) this;
        }

        public Criteria andPricechangeratioIn(List<Double> values) {
            addCriterion("priceChangeRatio in", values, "pricechangeratio");
            return (Criteria) this;
        }

        public Criteria andPricechangeratioNotIn(List<Double> values) {
            addCriterion("priceChangeRatio not in", values, "pricechangeratio");
            return (Criteria) this;
        }

        public Criteria andPricechangeratioBetween(Double value1, Double value2) {
            addCriterion("priceChangeRatio between", value1, value2, "pricechangeratio");
            return (Criteria) this;
        }

        public Criteria andPricechangeratioNotBetween(Double value1, Double value2) {
            addCriterion("priceChangeRatio not between", value1, value2, "pricechangeratio");
            return (Criteria) this;
        }

        public Criteria andBeijingtimeIsNull() {
            addCriterion("beijingTime is null");
            return (Criteria) this;
        }

        public Criteria andBeijingtimeIsNotNull() {
            addCriterion("beijingTime is not null");
            return (Criteria) this;
        }

        public Criteria andBeijingtimeEqualTo(String value) {
            addCriterion("beijingTime =", value, "beijingtime");
            return (Criteria) this;
        }

        public Criteria andBeijingtimeNotEqualTo(String value) {
            addCriterion("beijingTime <>", value, "beijingtime");
            return (Criteria) this;
        }

        public Criteria andBeijingtimeGreaterThan(String value) {
            addCriterion("beijingTime >", value, "beijingtime");
            return (Criteria) this;
        }

        public Criteria andBeijingtimeGreaterThanOrEqualTo(String value) {
            addCriterion("beijingTime >=", value, "beijingtime");
            return (Criteria) this;
        }

        public Criteria andBeijingtimeLessThan(String value) {
            addCriterion("beijingTime <", value, "beijingtime");
            return (Criteria) this;
        }

        public Criteria andBeijingtimeLessThanOrEqualTo(String value) {
            addCriterion("beijingTime <=", value, "beijingtime");
            return (Criteria) this;
        }

        public Criteria andBeijingtimeLike(String value) {
            addCriterion("beijingTime like", value, "beijingtime");
            return (Criteria) this;
        }

        public Criteria andBeijingtimeNotLike(String value) {
            addCriterion("beijingTime not like", value, "beijingtime");
            return (Criteria) this;
        }

        public Criteria andBeijingtimeIn(List<String> values) {
            addCriterion("beijingTime in", values, "beijingtime");
            return (Criteria) this;
        }

        public Criteria andBeijingtimeNotIn(List<String> values) {
            addCriterion("beijingTime not in", values, "beijingtime");
            return (Criteria) this;
        }

        public Criteria andBeijingtimeBetween(String value1, String value2) {
            addCriterion("beijingTime between", value1, value2, "beijingtime");
            return (Criteria) this;
        }

        public Criteria andBeijingtimeNotBetween(String value1, String value2) {
            addCriterion("beijingTime not between", value1, value2, "beijingtime");
            return (Criteria) this;
        }

        public Criteria andCurrenttimeIsNull() {
            addCriterion("currentTime is null");
            return (Criteria) this;
        }

        public Criteria andCurrenttimeIsNotNull() {
            addCriterion("currentTime is not null");
            return (Criteria) this;
        }

        public Criteria andCurrenttimeEqualTo(String value) {
            addCriterion("currentTime =", value, "currenttime");
            return (Criteria) this;
        }

        public Criteria andCurrenttimeNotEqualTo(String value) {
            addCriterion("currentTime <>", value, "currenttime");
            return (Criteria) this;
        }

        public Criteria andCurrenttimeGreaterThan(String value) {
            addCriterion("currentTime >", value, "currenttime");
            return (Criteria) this;
        }

        public Criteria andCurrenttimeGreaterThanOrEqualTo(String value) {
            addCriterion("currentTime >=", value, "currenttime");
            return (Criteria) this;
        }

        public Criteria andCurrenttimeLessThan(String value) {
            addCriterion("currentTime <", value, "currenttime");
            return (Criteria) this;
        }

        public Criteria andCurrenttimeLessThanOrEqualTo(String value) {
            addCriterion("currentTime <=", value, "currenttime");
            return (Criteria) this;
        }

        public Criteria andCurrenttimeLike(String value) {
            addCriterion("currentTime like", value, "currenttime");
            return (Criteria) this;
        }

        public Criteria andCurrenttimeNotLike(String value) {
            addCriterion("currentTime not like", value, "currenttime");
            return (Criteria) this;
        }

        public Criteria andCurrenttimeIn(List<String> values) {
            addCriterion("currentTime in", values, "currenttime");
            return (Criteria) this;
        }

        public Criteria andCurrenttimeNotIn(List<String> values) {
            addCriterion("currentTime not in", values, "currenttime");
            return (Criteria) this;
        }

        public Criteria andCurrenttimeBetween(String value1, String value2) {
            addCriterion("currentTime between", value1, value2, "currenttime");
            return (Criteria) this;
        }

        public Criteria andCurrenttimeNotBetween(String value1, String value2) {
            addCriterion("currentTime not between", value1, value2, "currenttime");
            return (Criteria) this;
        }

        public Criteria andOpenIsNull() {
            addCriterion("open is null");
            return (Criteria) this;
        }

        public Criteria andOpenIsNotNull() {
            addCriterion("open is not null");
            return (Criteria) this;
        }

        public Criteria andOpenEqualTo(Float value) {
            addCriterion("open =", value, "open");
            return (Criteria) this;
        }

        public Criteria andOpenNotEqualTo(Float value) {
            addCriterion("open <>", value, "open");
            return (Criteria) this;
        }

        public Criteria andOpenGreaterThan(Float value) {
            addCriterion("open >", value, "open");
            return (Criteria) this;
        }

        public Criteria andOpenGreaterThanOrEqualTo(Float value) {
            addCriterion("open >=", value, "open");
            return (Criteria) this;
        }

        public Criteria andOpenLessThan(Float value) {
            addCriterion("open <", value, "open");
            return (Criteria) this;
        }

        public Criteria andOpenLessThanOrEqualTo(Float value) {
            addCriterion("open <=", value, "open");
            return (Criteria) this;
        }

        public Criteria andOpenIn(List<Float> values) {
            addCriterion("open in", values, "open");
            return (Criteria) this;
        }

        public Criteria andOpenNotIn(List<Float> values) {
            addCriterion("open not in", values, "open");
            return (Criteria) this;
        }

        public Criteria andOpenBetween(Float value1, Float value2) {
            addCriterion("open between", value1, value2, "open");
            return (Criteria) this;
        }

        public Criteria andOpenNotBetween(Float value1, Float value2) {
            addCriterion("open not between", value1, value2, "open");
            return (Criteria) this;
        }

        public Criteria andCloseIsNull() {
            addCriterion("close is null");
            return (Criteria) this;
        }

        public Criteria andCloseIsNotNull() {
            addCriterion("close is not null");
            return (Criteria) this;
        }

        public Criteria andCloseEqualTo(Float value) {
            addCriterion("close =", value, "close");
            return (Criteria) this;
        }

        public Criteria andCloseNotEqualTo(Float value) {
            addCriterion("close <>", value, "close");
            return (Criteria) this;
        }

        public Criteria andCloseGreaterThan(Float value) {
            addCriterion("close >", value, "close");
            return (Criteria) this;
        }

        public Criteria andCloseGreaterThanOrEqualTo(Float value) {
            addCriterion("close >=", value, "close");
            return (Criteria) this;
        }

        public Criteria andCloseLessThan(Float value) {
            addCriterion("close <", value, "close");
            return (Criteria) this;
        }

        public Criteria andCloseLessThanOrEqualTo(Float value) {
            addCriterion("close <=", value, "close");
            return (Criteria) this;
        }

        public Criteria andCloseIn(List<Float> values) {
            addCriterion("close in", values, "close");
            return (Criteria) this;
        }

        public Criteria andCloseNotIn(List<Float> values) {
            addCriterion("close not in", values, "close");
            return (Criteria) this;
        }

        public Criteria andCloseBetween(Float value1, Float value2) {
            addCriterion("close between", value1, value2, "close");
            return (Criteria) this;
        }

        public Criteria andCloseNotBetween(Float value1, Float value2) {
            addCriterion("close not between", value1, value2, "close");
            return (Criteria) this;
        }

        public Criteria andMaxpriceIsNull() {
            addCriterion("maxPrice is null");
            return (Criteria) this;
        }

        public Criteria andMaxpriceIsNotNull() {
            addCriterion("maxPrice is not null");
            return (Criteria) this;
        }

        public Criteria andMaxpriceEqualTo(Float value) {
            addCriterion("maxPrice =", value, "maxprice");
            return (Criteria) this;
        }

        public Criteria andMaxpriceNotEqualTo(Float value) {
            addCriterion("maxPrice <>", value, "maxprice");
            return (Criteria) this;
        }

        public Criteria andMaxpriceGreaterThan(Float value) {
            addCriterion("maxPrice >", value, "maxprice");
            return (Criteria) this;
        }

        public Criteria andMaxpriceGreaterThanOrEqualTo(Float value) {
            addCriterion("maxPrice >=", value, "maxprice");
            return (Criteria) this;
        }

        public Criteria andMaxpriceLessThan(Float value) {
            addCriterion("maxPrice <", value, "maxprice");
            return (Criteria) this;
        }

        public Criteria andMaxpriceLessThanOrEqualTo(Float value) {
            addCriterion("maxPrice <=", value, "maxprice");
            return (Criteria) this;
        }

        public Criteria andMaxpriceIn(List<Float> values) {
            addCriterion("maxPrice in", values, "maxprice");
            return (Criteria) this;
        }

        public Criteria andMaxpriceNotIn(List<Float> values) {
            addCriterion("maxPrice not in", values, "maxprice");
            return (Criteria) this;
        }

        public Criteria andMaxpriceBetween(Float value1, Float value2) {
            addCriterion("maxPrice between", value1, value2, "maxprice");
            return (Criteria) this;
        }

        public Criteria andMaxpriceNotBetween(Float value1, Float value2) {
            addCriterion("maxPrice not between", value1, value2, "maxprice");
            return (Criteria) this;
        }

        public Criteria andMinpriceIsNull() {
            addCriterion("minPrice is null");
            return (Criteria) this;
        }

        public Criteria andMinpriceIsNotNull() {
            addCriterion("minPrice is not null");
            return (Criteria) this;
        }

        public Criteria andMinpriceEqualTo(Float value) {
            addCriterion("minPrice =", value, "minprice");
            return (Criteria) this;
        }

        public Criteria andMinpriceNotEqualTo(Float value) {
            addCriterion("minPrice <>", value, "minprice");
            return (Criteria) this;
        }

        public Criteria andMinpriceGreaterThan(Float value) {
            addCriterion("minPrice >", value, "minprice");
            return (Criteria) this;
        }

        public Criteria andMinpriceGreaterThanOrEqualTo(Float value) {
            addCriterion("minPrice >=", value, "minprice");
            return (Criteria) this;
        }

        public Criteria andMinpriceLessThan(Float value) {
            addCriterion("minPrice <", value, "minprice");
            return (Criteria) this;
        }

        public Criteria andMinpriceLessThanOrEqualTo(Float value) {
            addCriterion("minPrice <=", value, "minprice");
            return (Criteria) this;
        }

        public Criteria andMinpriceIn(List<Float> values) {
            addCriterion("minPrice in", values, "minprice");
            return (Criteria) this;
        }

        public Criteria andMinpriceNotIn(List<Float> values) {
            addCriterion("minPrice not in", values, "minprice");
            return (Criteria) this;
        }

        public Criteria andMinpriceBetween(Float value1, Float value2) {
            addCriterion("minPrice between", value1, value2, "minprice");
            return (Criteria) this;
        }

        public Criteria andMinpriceNotBetween(Float value1, Float value2) {
            addCriterion("minPrice not between", value1, value2, "minprice");
            return (Criteria) this;
        }

        public Criteria andVolumeIsNull() {
            addCriterion("volume is null");
            return (Criteria) this;
        }

        public Criteria andVolumeIsNotNull() {
            addCriterion("volume is not null");
            return (Criteria) this;
        }

        public Criteria andVolumeEqualTo(Long value) {
            addCriterion("volume =", value, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeNotEqualTo(Long value) {
            addCriterion("volume <>", value, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeGreaterThan(Long value) {
            addCriterion("volume >", value, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeGreaterThanOrEqualTo(Long value) {
            addCriterion("volume >=", value, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeLessThan(Long value) {
            addCriterion("volume <", value, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeLessThanOrEqualTo(Long value) {
            addCriterion("volume <=", value, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeIn(List<Long> values) {
            addCriterion("volume in", values, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeNotIn(List<Long> values) {
            addCriterion("volume not in", values, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeBetween(Long value1, Long value2) {
            addCriterion("volume between", value1, value2, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeNotBetween(Long value1, Long value2) {
            addCriterion("volume not between", value1, value2, "volume");
            return (Criteria) this;
        }

        public Criteria andMarketcapitalizationIsNull() {
            addCriterion("marketCapitalization is null");
            return (Criteria) this;
        }

        public Criteria andMarketcapitalizationIsNotNull() {
            addCriterion("marketCapitalization is not null");
            return (Criteria) this;
        }

        public Criteria andMarketcapitalizationEqualTo(Long value) {
            addCriterion("marketCapitalization =", value, "marketcapitalization");
            return (Criteria) this;
        }

        public Criteria andMarketcapitalizationNotEqualTo(Long value) {
            addCriterion("marketCapitalization <>", value, "marketcapitalization");
            return (Criteria) this;
        }

        public Criteria andMarketcapitalizationGreaterThan(Long value) {
            addCriterion("marketCapitalization >", value, "marketcapitalization");
            return (Criteria) this;
        }

        public Criteria andMarketcapitalizationGreaterThanOrEqualTo(Long value) {
            addCriterion("marketCapitalization >=", value, "marketcapitalization");
            return (Criteria) this;
        }

        public Criteria andMarketcapitalizationLessThan(Long value) {
            addCriterion("marketCapitalization <", value, "marketcapitalization");
            return (Criteria) this;
        }

        public Criteria andMarketcapitalizationLessThanOrEqualTo(Long value) {
            addCriterion("marketCapitalization <=", value, "marketcapitalization");
            return (Criteria) this;
        }

        public Criteria andMarketcapitalizationIn(List<Long> values) {
            addCriterion("marketCapitalization in", values, "marketcapitalization");
            return (Criteria) this;
        }

        public Criteria andMarketcapitalizationNotIn(List<Long> values) {
            addCriterion("marketCapitalization not in", values, "marketcapitalization");
            return (Criteria) this;
        }

        public Criteria andMarketcapitalizationBetween(Long value1, Long value2) {
            addCriterion("marketCapitalization between", value1, value2, "marketcapitalization");
            return (Criteria) this;
        }

        public Criteria andMarketcapitalizationNotBetween(Long value1, Long value2) {
            addCriterion("marketCapitalization not between", value1, value2, "marketcapitalization");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table stock
     *
     * @mbggenerated do_not_delete_during_merge Wed Apr 12 19:45:01 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table stock
     *
     * @mbggenerated Wed Apr 12 19:45:01 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}