package com.nju.qrs.model;

public class Stock {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.stockNum
     *
     * @mbggenerated Wed Apr 12 18:54:21 CST 2017
     */
    private String stockNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.stockName
     *
     * @mbggenerated Wed Apr 12 18:54:21 CST 2017
     */
    private String stockName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.marketClosed
     *
     * @mbggenerated Wed Apr 12 18:54:21 CST 2017
     */
    private Boolean marketClosed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.currentPrice
     *
     * @mbggenerated Wed Apr 12 18:54:21 CST 2017
     */
    private Float currentPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.changeAmount
     *
     * @mbggenerated Wed Apr 12 18:54:21 CST 2017
     */
    private Float changeAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.priceChangeRatio
     *
     * @mbggenerated Wed Apr 12 18:54:21 CST 2017
     */
    private Double priceChangeRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.beijingTime
     *
     * @mbggenerated Wed Apr 12 18:54:21 CST 2017
     */
    private String beijingTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.currentTime
     *
     * @mbggenerated Wed Apr 12 18:54:21 CST 2017
     */
    private String currentTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.open
     *
     * @mbggenerated Wed Apr 12 18:54:21 CST 2017
     */
    private Float open;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.close
     *
     * @mbggenerated Wed Apr 12 18:54:21 CST 2017
     */
    private Float close;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.maxPrice
     *
     * @mbggenerated Wed Apr 12 18:54:21 CST 2017
     */
    private Float maxPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.minPrice
     *
     * @mbggenerated Wed Apr 12 18:54:21 CST 2017
     */
    private Float minPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.volume
     *
     * @mbggenerated Wed Apr 12 18:54:21 CST 2017
     */
    private Long volume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.marketCapitalization
     *
     * @mbggenerated Wed Apr 12 18:54:21 CST 2017
     */
    private Long marketCapitalization;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.stockNum
     *
     * @return the value of stock.stockNum
     *
     * @mbggenerated Wed Apr 12 18:54:21 CST 2017
     */
    public String getStockNum() {
        return stockNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.stockNum
     *
     * @param stockNum the value for stock.stockNum
     *
     * @mbggenerated Wed Apr 12 18:54:21 CST 2017
     */
    public void setStockNum(String stockNum) {
        this.stockNum = stockNum == null ? null : stockNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.stockName
     *
     * @return the value of stock.stockName
     *
     * @mbggenerated Wed Apr 12 18:54:21 CST 2017
     */
    public String getStockName() {
        return stockName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.stockName
     *
     * @param stockName the value for stock.stockName
     *
     * @mbggenerated Wed Apr 12 18:54:21 CST 2017
     */
    public void setStockName(String stockName) {
        this.stockName = stockName == null ? null : stockName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.marketClosed
     *
     * @return the value of stock.marketClosed
     *
     * @mbggenerated Wed Apr 12 18:54:21 CST 2017
     */
    public Boolean getMarketClosed() {
        return marketClosed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.marketClosed
     *
     * @param marketClosed the value for stock.marketClosed
     *
     * @mbggenerated Wed Apr 12 18:54:21 CST 2017
     */
    public void setMarketClosed(Boolean marketClosed) {
        this.marketClosed = marketClosed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.currentPrice
     *
     * @return the value of stock.currentPrice
     *
     * @mbggenerated Wed Apr 12 18:54:21 CST 2017
     */
    public Float getCurrentPrice() {
        return currentPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.currentPrice
     *
     * @param currentPrice the value for stock.currentPrice
     *
     * @mbggenerated Wed Apr 12 18:54:21 CST 2017
     */
    public void setCurrentPrice(Float currentPrice) {
        this.currentPrice = currentPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.changeAmount
     *
     * @return the value of stock.changeAmount
     *
     * @mbggenerated Wed Apr 12 18:54:21 CST 2017
     */
    public Float getChangeAmount() {
        return changeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.changeAmount
     *
     * @param changeAmount the value for stock.changeAmount
     *
     * @mbggenerated Wed Apr 12 18:54:21 CST 2017
     */
    public void setChangeAmount(Float changeAmount) {
        this.changeAmount = changeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.priceChangeRatio
     *
     * @return the value of stock.priceChangeRatio
     *
     * @mbggenerated Wed Apr 12 18:54:21 CST 2017
     */
    public Double getPriceChangeRatio() {
        return priceChangeRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.priceChangeRatio
     *
     * @param priceChangeRatio the value for stock.priceChangeRatio
     *
     * @mbggenerated Wed Apr 12 18:54:21 CST 2017
     */
    public void setPriceChangeRatio(Double priceChangeRatio) {
        this.priceChangeRatio = priceChangeRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.beijingTime
     *
     * @return the value of stock.beijingTime
     *
     * @mbggenerated Wed Apr 12 18:54:21 CST 2017
     */
    public String getBeijingTime() {
        return beijingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.beijingTime
     *
     * @param beijingTime the value for stock.beijingTime
     *
     * @mbggenerated Wed Apr 12 18:54:21 CST 2017
     */
    public void setBeijingTime(String beijingTime) {
        this.beijingTime = beijingTime == null ? null : beijingTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.currentTime
     *
     * @return the value of stock.currentTime
     *
     * @mbggenerated Wed Apr 12 18:54:21 CST 2017
     */
    public String getCurrentTime() {
        return currentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.currentTime
     *
     * @param currentTime the value for stock.currentTime
     *
     * @mbggenerated Wed Apr 12 18:54:21 CST 2017
     */
    public void setCurrentTime(String currentTime) {
        this.currentTime = currentTime == null ? null : currentTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.open
     *
     * @return the value of stock.open
     *
     * @mbggenerated Wed Apr 12 18:54:21 CST 2017
     */
    public Float getOpen() {
        return open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.open
     *
     * @param open the value for stock.open
     *
     * @mbggenerated Wed Apr 12 18:54:21 CST 2017
     */
    public void setOpen(Float open) {
        this.open = open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.close
     *
     * @return the value of stock.close
     *
     * @mbggenerated Wed Apr 12 18:54:21 CST 2017
     */
    public Float getClose() {
        return close;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.close
     *
     * @param close the value for stock.close
     *
     * @mbggenerated Wed Apr 12 18:54:21 CST 2017
     */
    public void setClose(Float close) {
        this.close = close;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.maxPrice
     *
     * @return the value of stock.maxPrice
     *
     * @mbggenerated Wed Apr 12 18:54:21 CST 2017
     */
    public Float getMaxPrice() {
        return maxPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.maxPrice
     *
     * @param maxPrice the value for stock.maxPrice
     *
     * @mbggenerated Wed Apr 12 18:54:21 CST 2017
     */
    public void setMaxPrice(Float maxPrice) {
        this.maxPrice = maxPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.minPrice
     *
     * @return the value of stock.minPrice
     *
     * @mbggenerated Wed Apr 12 18:54:21 CST 2017
     */
    public Float getMinPrice() {
        return minPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.minPrice
     *
     * @param minPrice the value for stock.minPrice
     *
     * @mbggenerated Wed Apr 12 18:54:21 CST 2017
     */
    public void setMinPrice(Float minPrice) {
        this.minPrice = minPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.volume
     *
     * @return the value of stock.volume
     *
     * @mbggenerated Wed Apr 12 18:54:21 CST 2017
     */
    public Long getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.volume
     *
     * @param volume the value for stock.volume
     *
     * @mbggenerated Wed Apr 12 18:54:21 CST 2017
     */
    public void setVolume(Long volume) {
        this.volume = volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.marketCapitalization
     *
     * @return the value of stock.marketCapitalization
     *
     * @mbggenerated Wed Apr 12 18:54:21 CST 2017
     */
    public Long getMarketCapitalization() {
        return marketCapitalization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.marketCapitalization
     *
     * @param marketCapitalization the value for stock.marketCapitalization
     *
     * @mbggenerated Wed Apr 12 18:54:21 CST 2017
     */
    public void setMarketCapitalization(Long marketCapitalization) {
        this.marketCapitalization = marketCapitalization;
    }
}