package com.nju.qrs.mapper;

import com.nju.qrs.model.StockPriceHis;
import com.nju.qrs.model.StockPriceHisExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface StockPriceHisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_price_his
     *
     * @mbggenerated Wed Apr 12 19:45:01 CST 2017
     */
    int countByExample(StockPriceHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_price_his
     *
     * @mbggenerated Wed Apr 12 19:45:01 CST 2017
     */
    int deleteByExample(StockPriceHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_price_his
     *
     * @mbggenerated Wed Apr 12 19:45:01 CST 2017
     */
    int insert(StockPriceHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_price_his
     *
     * @mbggenerated Wed Apr 12 19:45:01 CST 2017
     */
    int insertSelective(StockPriceHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_price_his
     *
     * @mbggenerated Wed Apr 12 19:45:01 CST 2017
     */
    List<StockPriceHis> selectByExample(StockPriceHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_price_his
     *
     * @mbggenerated Wed Apr 12 19:45:01 CST 2017
     */
    int updateByExampleSelective(@Param("record") StockPriceHis record, @Param("example") StockPriceHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_price_his
     *
     * @mbggenerated Wed Apr 12 19:45:01 CST 2017
     */
    int updateByExample(@Param("record") StockPriceHis record, @Param("example") StockPriceHisExample example);
}